### ISSUE TITLE
delete plz

### ISSUE THREAD

**Issue by flippz** [dave-p/TVHadmin-JS#3]
never mind...was chrome glitching it seems

**Comment by dave-p** [comment]
OK. I took a look at the code and fixed a couple of small errors anyway ;-)

**Comment by flippz** [comment]
Nice
What im actually looking for is a webui that can act almost like yours but
when i press the program it opens the stream in chrome automatically. Im
using a profile in tvheadend so that chrome can actually play the streams.
Anyway to do this?

tir. 17. mai 2022, 13:51 skrev dave-p ***@***.***>:

**Comment by dave-p** [comment]
This should work already, if you click on a programme currently running (ie in green) TVH sends a media playlist to the browser which it should open with its default media player.

**Comment by flippz** [comment]
I am no coder but i changed
this:
 if (p.onNow) s += `<a href='/play/stream/channel/${c.uuid}?title=${c.name}'><div class='item ${colour}' style='width: ${pc}%;' title='${subtitle}'>${p.title}</div></a>`;

to this:
  if (p.onNow) s += `<a href='/stream/channel/${c.uuid}'><div class='item ${colour}' style='width: ${pc}%;' title='${subtitle}'>${p.title}</div></a>`;

and now it works
i have a profile i called p.mp4 witch is set to default if that has any say in it

**Comment by dave-p** [comment]
I made a change a few days ago so the downloaded playlist always has the .m3u8 file extension. On Chrome (and Brave) the playlist downloads and is listed at the bottom of the browser screen. If you right-click on the file name and select "Always open files of this type", then all future streams will automatically open in your default viewer.
