### ISSUE TITLE
Series recording in Timeline view

### ISSUE THREAD

**Issue by Eyerex** [dave-p/TVHadmin-JS#5]
Hello not really a problem but wondered if series recording could be added as a option when in Timeline view

**Comment by dave-p** [comment]
Technically possible of course. I'll add it to the possible 'todo' list.

**Comment by Eyerex** [comment]
Cheers

**Comment by dave-p** [comment]
That was (a little) easier than I expected...

I've created a new branch called 'seriesrec' with the changes. It's tested on Firefox, Chromium and Bromite (Android). Are you able to test it on your system?

**Comment by Eyerex** [comment]
Yes no problem testing will do it now

**Comment by Eyerex** [comment]
Wasn't sure if i could just download the TVHadmin-JS-master.zip from seriesrec which didn't work ie new option didn't show up so copied the code from timeline.html and made a new file which worked and new option showed up

Big thanks for doing this

**Comment by dave-p** [comment]
I've pushed the new feature to master (with a small change to improve the layout of the dialog).
Thanks for the suggestion - it's always interesting to see how others use the software!
Closing.
