### ISSUE TITLE
Channel icon not shown if no EPG data

### ISSUE THREAD

**Issue by hal2000gh** [dave-p/TVHadmin-JS#9]
The "What's On Now" view, does not show the channel icon if there is no EPG data:

![grafik](https://user-images.githubusercontent.com/16773822/203277468-f59afe68-22b8-44d1-b8dd-38dfa74cfdc6.png)

My TVH-Version is 4.2.8-36~g5bdcfd8ac

Great front-end, thanks!
Peter

**Comment by dave-p** [comment]
Github rudely closed the issue without giving me time to say thanks for the bug report!
